language: node_js
node_js:
  - 8

sudo: required

addons:
  chrome: stable

stages:
  - name: test

jobs:
  fail_fast: true
  include:
    - stage: test
      name: "Unit tests and linting"
      install: npm ci
      script: npm test