version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing Meteor
      - curl https://install.meteor.com/ | sh
  pre_build:
    commands:
      - echo Displaying folder structure
      - ls
  build:
    commands:
      - echo Build started on `date`
      - meteor npm install
      - meteor build . --allow-superuser --directory
      - cd bundle/programs/server && npm install --production 
  post_build:
    commands:
      - cd ../../../
      - cp package.json ./bundle/package.json
      - ls -la
      - ls -la ./bundle/
      - echo Build completed on `date`
artifacts:
  base-directory: bundle # Bundle contains the built code
  files:
    - ./**/* # Include all files 
